#!/bin/bash

set -e

os_name=$(grep '^NAME=' /etc/os-release 2>/dev/null | cut -d= -f2- | tr -d '"')

if [[ $# -eq 1 ]]; then
  case "$1" in
    -c)
      echo "$os_name"
      exit 0
      ;;
    -l)
      echo "$os_name"
      exit 0
      ;;
    stable)
      exit 0
      ;;
    *)
      echo "Invalid option. Usage: steamos-select-branch <stable|-c|-l>" 1>&2
      exit 1
      ;;
  esac
fi

echo "Usage: steamos-select-branch <stable|-c|-l>" 1>&2
