[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell
[Autologin]
Relogin=true
#This is only for first boot as a file that overrides this gets created once /usr/lib/os-session-select runs
Session=gamescope-session.desktop
User=deck
[Wayland]
CompositorCommand=kwin_wayland --drm --locale1
