#!/usr/bin/bash
inverted=false
while getopts "i" flag; do
 case $flag in
   i) inverted=true ;;
 esac
done
#Exits with 0 for Valve handhelds unless inverted
SYS_ID="$(cat /sys/devices/virtual/dmi/id/product_name)"
if [[ ":Jupiter:Galileo:" =~ ":$SYS_ID:" ]]; then
	if $inverted; then
		exit 1
	else
		exit 0
	fi
fi
if $inverted; then
	exit 0
else
	exit 1
fi